language: python
python:
    - "2.7"
install: pip install -r requirements.txt
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - cp database.yml.travis database.yml
    - psql -c 'create database "blogful-test";' -U nitrous
script:
    - PYTHONPATH=. python tests/test_filters.py
    - PYTHONPATH=. python tests/test_views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py
    # Add any other tests here